const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Consequat nisl vel pretium lectus quam id. Erat velit scelerisque in dictum non consectetur a erat nam. Euismod nisi porta lorem mollis. Lacus sed viverra tellus in hac habitasse platea dictumst. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Ac placerat vestibulum lectus mauris. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Amet mauris commodo quis imperdiet massa tincidunt nunc. Pharetra diam sit amet nisl suscipit adipiscing. Iaculis urna id volutpat lacus. Augue eget arcu dictum varius duis at consectetur.

Sit amet aliquam id diam maecenas ultricies mi. Sed sed risus pretium quam vulputate. Sodales ut eu sem integer vitae justo eget magna. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Sapien pellentesque habitant morbi tristique senectus et netus. Amet risus nullam eget felis eget nunc lobortis mattis. Sagittis purus sit amet volutpat consequat mauris. Aliquet risus feugiat in ante metus dictum at tempor commodo. Tortor posuere ac ut consequat semper viverra nam libero justo. In ante metus dictum at tempor commodo ullamcorper a lacus. Natoque penatibus et magnis dis. Montes nascetur ridiculus mus mauris vitae ultricies leo. Facilisi cras fermentum odio eu feugiat. Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Porttitor lacus luctus accumsan tortor posuere ac ut consequat.

Enim eu turpis egestas pretium aenean pharetra magna ac. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Fusce ut placerat orci nulla. Enim nec dui nunc mattis enim. Nunc sed id semper risus in hendrerit. Mauris ultrices eros in cursus turpis massa. Convallis posuere morbi leo urna molestie. Ornare arcu odio ut sem nulla pharetra diam. Tempor orci eu lobortis elementum. Viverra maecenas accumsan lacus vel facilisis volutpat est velit.

Id semper risus in hendrerit gravida rutrum. Ridiculus mus mauris vitae ultricies leo. Varius duis at consectetur lorem donec massa. Turpis cursus in hac habitasse platea dictumst quisque. Arcu cursus euismod quis viverra nibh cras. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. At auctor urna nunc id. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Quisque sagittis purus sit amet volutpat consequat mauris. Metus dictum at tempor commodo ullamcorper a. Feugiat vivamus at augue eget arcu dictum varius. Cum sociis natoque penatibus et magnis dis parturient montes.

Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Donec adipiscing tristique risus nec. Potenti nullam ac tortor vitae purus faucibus ornare. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam purus. Urna id volutpat lacus laoreet non curabitur gravida arcu. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Nullam vehicula ipsum a arcu cursus. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Quis risus sed vulputate odio. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Mauris augue neque gravida in fermentum et sollicitudin ac. Turpis egestas integer eget aliquet nibh praesent tristique.`;

export default lorem;
